### ISSUE TITLE
Should detect client reporting status

### ISSUE THREAD

**Issue by a-schild** [zbx-sadman/WSUS#2]
On one of our client sites we had WSUS installed and the zabbix monitoring.
Everything worked fine, unless someone messed up the IIS config, which resulted in clients no beeing able to connect to the wsus server and not reporting to it.

The zabbix WSUS monitoring script/template did not report/discover this problem.
It would be nice to be receive a trigger which alerts in such conditions.

One way to detect this would be to look for the date of the last client reporting to the server and then trigger if it's older than 5-10 days.

Also another trigger which looks if 80% of the clients have reported in the last 2 weeks would be helpfull to catch such cases.

**Comment by zbx-sadman** [comment]
I've add new virtual key _ComputerTargetsNotUpdatedWithin_ for _ComputerGroup_ object .

With _Value_ cmdline option and _Count action_ script will return number of clents, that updated within a days:

```
...
# $Value - number of days

$Today = Get-Date;
$Objects = $ComputerTargetGroups | % { $_.GetTotalSummaryPerComputerTarget() } |
    Where { (New-TimeSpan -Start $_.LastUpdated -End $Today).Days -le $Value }
...
<return number of $Objects>
```
For example:

```
powershell -File "wsus_miner.ps1" -Action Count -Object "computerGroup" -Key "ComputerTargetsNotUpdatedWithin" -Value 3 -Verbose  -defaultConsoleWidth

Verbose: 02/21/2018 15:21:12 Test 'UpdateServices' module state
Verbose: 02/21/2018 15:21:12 Loading 'Microsoft.UpdateServices.Administration' assembly from file
Verbose: 02/21/2018 15:21:12 Trying to connect to local WSUS Server
Verbose: 02/21/2018 15:21:13 Connection established
Verbose: 02/21/2018 15:21:13 Creating collection of specified object: 'computerGroup'
Verbose: 02/21/2018 15:21:21 Collection created, begin processing its with action: 'Count'
Verbose: 02/21/2018 15:21:21 Counting objects
Verbose: 02/21/2018 15:21:21 Finishing
47
```

Number of computers that updated 21 Feb, 19 Feb. 18 Feb is returned if script will started 21 Feb.

I think you can specify $Value as 5 (days) and catch 0 in trigger. Then you can say, that no one client was updated within 5 days and it's a problem.

This is that you imagine?

P.S. _LastUpdated_ property is used because i see no LastPeported or similar prop.

**Comment by zbx-sadman** [comment]
I've found _LastReportedStatusTime_ prop:

```
 'ComputerTargetsNotReportedWithin' {
     $Today = Get-Date;
     $ComputerTargetGroups | % { $_.GetComputerTargets() } | Sort-Object -Property Id -Unique |
          Where { (New-TimeSpan -Start $_.LastReportedStatusTime -End $Today).Days -le $Value } 
```

**Comment by a-schild** [comment]
I think monitoring both would be good, and when the delta between both "is too big", then fire a trigger

**Comment by zbx-sadman** [comment]
You can test it:
https://github.com/zbx-sadman/WSUS/tree/master/dev

Please send feedback to me, because i found something strange in the WSUS API answer. Some computers seems "Updated" but not "Reported".

Make                      : MSI
Model                     : MS-7721
Id                            : f954b809-6da3-4c73-af02-a49765ad9350
OSDescription        : Windows 6.3
ComputerRole        : Workstation
**LastReportedStatusTime    : 1/31/2018 2:26:27 PM**

 but 

ComputerTargetId            : f954b809-6da3-4c73-af02-a49765ad9350
**LastUpdated                  : 2/24/2018 12:20:37 AM**

**Comment by a-schild** [comment]
Thanks, yes I see this too on my system.
This can occur when the WSUS server has not yet received a complete status report from the client, but the client has still installed updates since then.
This is also a condition which should be observed, so the script is working fine, the WSUS stuff seems to have problems receiving reports from some clients.

The trigger seems to have no effect, but I must look into more details to be sure.

![2018-02-26 12_37_49-sv04-ads - teamviewer](https://user-images.githubusercontent.com/1441009/36668545-eea12f40-1af1-11e8-8653-dbb6d2bf79c5.png)
